### PR TITLE
Dev/borroving model

### PR DESCRIPTION
**Pull request by BornToLivee**
add model + validation in model + tests
 i know its better to add validation in serializer, but 
 
image

### CODE REVIEW

**Review by b3v3kt0r — COMMENTED** [review]
fayno

**Comment by lilarin** [comment]
Can you expand str method to add user label, please?
It`s necessary for telegram notofication couse it returns str representation of created borrowing

**Review by lilarin — APPROVED** [review]
Nice! 😎

**Review by b3v3kt0r — COMMENTED** [review]
+

**Review by b3v3kt0r — COMMENTED** [review]
++

**Review by b3v3kt0r — APPROVED** [review]

**Pull request merged**
